version: "3"

networks:
  proxiable:
    name: proxiable
    external: true
  directus:
    name: directus
  keycloak:
    name: keycloak

services:
  collectivo:
    container_name: collectivo
    build: ./collectivo
    networks:
      - directus
      - proxiable
    environment:
      NUXT_API_TOKEN: ${COLLECTIVO_API_TOKEN}
      NUXT_DIRECTUS_ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      NUXT_DIRECTUS_ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      NUXT_KEYCLOAK_ADMIN_CLIENT: ${KEYCLOAK_ADMIN_CLIENT}
      NUXT_KEYCLOAK_ADMIN_SECRET: ${KEYCLOAK_ADMIN_SECRET}
      NUXT_PUBLIC_COLLECTIVO_URL: ${COLLECTIVO_URL}
      NUXT_PUBLIC_DEFAULT_LOCAL: ${COLLECTIVO_DEFAULT_LOCAL}
      NUXT_PUBLIC_DIRECTUS_URL: ${DIRECTUS_URL}
      NUXT_PUBLIC_KEYCLOAK_URL: ${KEYCLOAK_URL}
      NUXT_PUBLIC_KEYCLOAK_REALM: ${KEYCLOAK_REALM}
    depends_on:
      keycloak:
        condition: service_healthy
      directus-db:
        condition: service_healthy

  directus-db:
    container_name: directus-db
    image: postgis/postgis:15-3.4-alpine
    volumes:
      - directus-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: ${DIRECTUS_DB_PASSWORD}
      POSTGRES_DB: "directus"
    networks:
      - directus

  directus-cache:
    container_name: directus-cache
    image: redis:6
    networks:
      - directus

  directus:
    image: directus/directus:10.8.3
    container_name: directus
    depends_on:
      - directus-db
      - directus-cache
    # TODO: Can below be removed?
    expose:
      - 8055
    networks:
      - proxiable
      - directus
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}

      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}

      DB_CLIENT: "pg"
      DB_HOST: "directus-db"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: ${DIRECTUS_DB_PASSWORD}

      # CACHE_ENABLED: "true"
      # CACHE_STORE: "redis"
      # REDIS: "redis://directus-cache:6379"

      WEBSOCKETS_ENABLED: true
      PUBLIC_URL: ${DIRECTUS_URL}

      AUTH_PROVIDERS: "keycloak"
      AUTH_KEYCLOAK_DRIVER: "openid"
      AUTH_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_DIRECTUS_CLIENT}
      AUTH_KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_DIRECTUS_SECRET}
      AUTH_KEYCLOAK_ISSUER_URL: "${KEYCLOAK_URL}/realms/collectivo/.well-known/openid-configuration"
      AUTH_KEYCLOAK_IDENTIFIER_KEY: "email"
      AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION: "true"

      REFRESH_TOKEN_COOKIE_DOMAIN: ${DIRECTUS_DOMAIN}
      REFRESH_TOKEN_COOKIE_SECURE: "true"
      REFRESH_TOKEN_COOKIE_SAME_SITE: "lax"

      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      # CORS_ORIGIN: "[${DIRECTUS_URL}, ${COLLECTIVO_URL}]"

  keycloak-db:
    image: postgres:15.4-alpine
    container_name: keycloak-db
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_URL}
      KEYCLOAK_IMPORT: /tmp/collectivo-realm.json
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: "keycloak"
      KC_DB_URL_HOST: "keycloak-db"
      KC_DB_URL_PORT: 5432
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro
      - ./keycloak/export:/tmp/export
    command: start --optimized --health-enabled true
    healthcheck:
      test: ["CMD", "curl", "-f", "${KEYCLOAK_URL}/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 20
    depends_on:
      - keycloak-db
    networks:
      - keycloak
      - proxiable

volumes:
  directus-db-data:
  keycloak-db-data:
