version: "3"

services:
  collectivo:
    container_name: collectivo
    build: ./collectivo
    environment:
      NUXT_RUN_MIGRATIONS: "true"
      NUXT_DIRECTUS_ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      NUXT_DIRECTUS_ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      NUXT_PUBLIC_COLLECTIVO_URL: ${COLLECTIVO_URL}
      NUXT_PUBLIC_DEFAULT_LOCAL: ${COLLECTIVO_DEFAULT_LOCAL}
      NUXT_PUBLIC_DIRECTUS_URL: ${DIRECTUS_URL}
      NUXT_PUBLIC_KEYCLOAK_URL: ${KEYCLOAK_URL}
      NUXT_PUBLIC_KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      NUXT_PUBLIC_KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT}
    depends_on:
      - keycloak
        # condition: service_healthy
      - directus
    ports:
      - "3000:3000"

  directus-db:
    container_name: directus-db
    image: postgis/postgis:15-3.4-alpine
    volumes:
      - collectivo-server-dev-directus-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: ${DIRECTUS_DB_PASSWORD}
      POSTGRES_DB: "directus"

  directus-cache:
    container_name: directus-cache
    image: redis:6

  directus:
    image: directus/directus:10.6.2
    container_name: directus
    depends_on:
      - keycloak
        # condition: service_healthy
      - directus-db
      - directus-cache
    ports:
      - "8055:8055"
    links:
      - keycloak
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}

      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}

      DB_CLIENT: "pg"
      DB_HOST: "directus-db"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: ${DIRECTUS_DB_PASSWORD}

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://directus-cache:6379"

      WEBSOCKETS_ENABLED: true
      PUBLIC_URL: ${DIRECTUS_URL}

      AUTH_PROVIDERS: "keycloak"
      AUTH_KEYCLOAK_DRIVER: "openid"
      AUTH_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_DIRECTUS_CLIENT}
      AUTH_KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_DIRECTUS_SECRET}
      AUTH_KEYCLOAK_ISSUER_URL: "${KEYCLOAK_URL}/realms/collectivo/.well-known/openid-configuration"
      AUTH_KEYCLOAK_IDENTIFIER_KEY: "email"
      AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION: "true"

      # CORS_ENABLED: "true"
      # CORS_ORIGIN: "true"

  keycloak-db:
    image: postgres:15.4-alpine
    container_name: keycloak-db
    volumes:
      - collectivo-server-dev-keycloak-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_URL}
      KEYCLOAK_IMPORT: /tmp/collectivo-realm.json
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: "keycloak"
      KC_DB_URL_HOST: "keycloak-db"
      KC_DB_URL_PORT: 5432
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro
      - ./keycloak/export:/tmp/export
      - ./keycloak/healthcheck.sh:/healthcheck.sh
    command: start-dev --import-realm
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8080/realms/master"]
      interval: 5s
      timeout: 2s
      retries: 15
    depends_on:
      - keycloak-db
    ports:
      - "8080:8080"

volumes:
  collectivo-server-dev-directus-db-data:
  collectivo-server-dev-keycloak-db-data:
