version: "3"

networks:
  proxiable:
    name: proxiable
    external: true
  directus:
    name: directus
  keycloak:
    name: keycloak

services:
  directus-db:
    container_name: directus-db
    image: postgis/postgis:15-3.4-alpine
    volumes:
      - directus-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: ${DIRECTUS_DB_PASSWORD}
      POSTGRES_DB: "directus"
    networks:
      - directus

  directus-cache:
    container_name: directus-cache
    image: redis:6
    networks:
      - directus

  directus:
    image: directus/directus:10.6.1
    container_name: directus
    depends_on:
      - directus-db
      - directus-cache
    expose:
      - 8055
    networks:
      - proxiable
      - directus
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}

      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}

      DB_CLIENT: "pg"
      DB_HOST: "directus-db"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: ${DIRECTUS_DB_PASSWORD}

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://directus-cache:6379"

      WEBSOCKETS_ENABLED: true
      PUBLIC_URL: ${DIRECTUS_URL}

  keycloak-db:
    image: postgres:14-alpine
    container_name: keycloak-db
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    networks:
      - keycloak

  keycloak:
    build: ./keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_URL}
      KEYCLOAK_IMPORT: /tmp/collectivo-realm.json
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: "keycloak"
      KC_DB_URL_HOST: "keycloak-db"
      KC_DB_URL_PORT: 5432
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
    volumes:
      - ./keycloak/import/collectivo-realm.json:/tmp/collectivo-realm.json
      - ./keycloak/themes/collectivo:/opt/keycloak/themes/collectivo
      - ./keycloak/imported/:/opt/keycloak/imported/
    depends_on:
      - keycloak-db
    networks:
      - keycloak

volumes:
  directus-db-data:
  keycloak-db-data:
